### ISSUE TITLE
Не находит файл

### ISSUE THREAD

**Issue by nijkor** [claradex/nativegallery#1]
На третьей строке файла /index.php скрипт обращается к /vendor/autoload.php, но такого файла нет.
![image](https://github.com/claradex/nativegallery/assets/165425781/76b9715e-aacb-4c59-ab93-0fe01d7a7337)

**Comment by themohooks** [comment]
`composer install`
Эту команду надо вписать в терминале в папке сайта

**Comment by nijkor** [comment]
Теперь требует конфиг
![image](https://github.com/claradex/nativegallery/assets/165425781/17a87e6b-e4ec-4e6e-baa6-9828bd24e3f5)
