### ISSUE TITLE
Error "Not found"

### ISSUE THREAD

**Issue by Lanmikeman** [claradex/nativegallery#10]
![image](https://github.com/user-attachments/assets/bfbf5159-8d2f-48a2-aa9f-ac07c2cf21e2)
При попытке залогиниться на поднятом сайте, выскакивает ошибка 404.
По мимо этого, есть ещё ошибки с загрузкой фото на сайт при выбранном в конфиге варианте "server" FILE_NOTSELECTED.

БД развернул корректно, разрешения на файлы закинул 33 id (www-data). В чём мб проблема?

**Comment by GeorgNation** [comment]
Это VPS/выделенный сервер или shared-хостинг

**Comment by Lanmikeman** [comment]
> Это VPS/выделенный сервер или shared-хостинг?

Свой сервак

**Comment by GeorgNation** [comment]
> > Это VPS/выделенный сервер или shared-хостинг?
> 
> Свой сервак 

Nginx или Apache?

**Comment by Lanmikeman** [comment]
> > > Это VPS/выделенный сервер или shared-хостинг?
> > 
> > 
> > Свой сервак
> 
> Nginx или Apache?

И то и другое пробовал

**Comment by GeorgNation** [comment]
Конфиги htaccess предназначены исключительно для Apache, попробуйте его
