### ISSUE TITLE
При загрузке файла на сервер с параметром 'server' файл не заливается

### ISSUE THREAD

**Issue by Lanmikeman** [claradex/nativegallery#11]
![image](https://github.com/user-attachments/assets/b0ec89a3-2897-4f5b-9baa-b601826d1093)
При удачной загрузке файла (по статусу в меню публикации), файл оказывается не загружен

**Comment by GeorgNation** [comment]
Можно логи веб-сервера (access/error для apache/другие логи других веб-серверов)?

**Comment by Lanmikeman** [comment]
https://pastebin.com/2jcyKXQR

**Comment by GeorgNation** [comment]
@Lanmikeman А лог ошибок?

**Comment by Lanmikeman** [comment]
https://pastebin.com/MuYdfmVu

**Comment by Lanmikeman** [comment]
Я просто хз в чём проблема, ибо я каталогу uploads права 777 выдал

**Comment by GeorgNation** [comment]
@Lanmikeman А конфиг движка был настроен на загрузку файлов в папку uploads?

**Comment by GeorgNation** [comment]
@Lanmikeman Можно скрин папки uploads?

**Comment by Lanmikeman** [comment]
@GeorgNation ага

**Comment by Lanmikeman** [comment]
@GeorgNation 
![image](https://github.com/user-attachments/assets/1921733c-f286-41b5-a9d0-f29c455796c1)

**Comment by Lanmikeman** [comment]
@GeorgNation вот скрин корневой папки сайта
![image](https://github.com/user-attachments/assets/503b78e2-f5e8-4581-af23-a632eefa8e4d)

**Comment by GeorgNation** [comment]
> @GeorgNation ![image](https://private-user-images.githubusercontent.com/22985934/367406059-1921733c-f286-41b5-a9d0-f29c455796c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTIwMzYsIm5iZiI6MTcyNjI1MTczNiwicGF0aCI6Ii8yMjk4NTkzNC8zNjc0MDYwNTktMTkyMTczM2MtZjI4Ni00MWI1LWE5ZDAtZjI5YzQ1NTc5NmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE4MjIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNjIwODliNGI1MmFlMDQwNzBlZTNkODNmMTY1YmQ4Y2E5ZmZiZjdlYWNmYWJhYzEzOGEyMDAzNmZlM2E2ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q-b0nThA3oiK6ShAuuJ53iWB5kbp5iqZQABNskvNV-U)

Судя по всему проблема с самим загрузчиком, надо будет разобраться

**Comment by GeorgNation** [comment]
Действительно нашлась проблема движка, вынес в issue #12

**Comment by GeorgNation** [comment]
Этот issue пока будет закрыт (далее #12 )
