### ISSUE TITLE
Загрузчик фото работает только с CDN несмотря на настройку конфига

### ISSUE THREAD

**Issue by GeorgNation** [claradex/nativegallery#12]
https://github.com/claradex/nativegallery/blob/main/app/Controllers/Api/Images/Upload.php

To-do:
 - [ ] исправить

**Comment by themohooks** [comment]
@GeorgNation дубликат #11

**Comment by GeorgNation** [comment]
> @GeorgNation дубликат #11

нет я его специально сюда вынес для удобства работы

**Comment by themohooks** [comment]
Исправлено в ecd1b0f.
