### ISSUE TITLE
Error with upload

### ISSUE THREAD

**Issue by Lanmikeman** [claradex/nativegallery#9]
Ошибка при загрузке файла: FILE_NOTSELECTED

![Снимок экрана (108)](https://github.com/user-attachments/assets/ea983b34-9ba0-40ba-914e-5028f3cfa929)

**Comment by themohooks** [comment]
Сейчас нет возможности проверить (https://t.me/nativegallery/53)

**Comment by themohooks** [comment]
Последнее обновление было опубликовано на сайт, исправляющее баг

**Comment by Lanmikeman** [comment]
На своем инстансе как пофиксить эту шнягу? Загрузка с использованием параметра в кофигах «server»
